"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-08-26 18:35:11.429390
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate renders postgresql.JSONB as JSONB(astext_type=Text()), a bare
# name it does not import. Kept here so generated migrations are runnable.
from sqlalchemy import Text  # noqa: F401
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('strategy_id', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('timeframe', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('audit', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('trades', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='backtest_dates_ordered'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index('backtest_strategy_created_idx', ['strategy_id', 'created_at'], unique=False)
        batch_op.create_index('backtest_symbol_created_idx', ['symbol', 'created_at'], unique=False)

    op.create_table('bots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('strategy_id', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('symbols', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('timeframe', sa.Text(), nullable=False),
    sa.Column('capital_budget', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('risk_limits', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("mode in ('paper', 'live')", name='bots_mode_check'),
    sa.CheckConstraint('capital_budget > 0', name='bots_capital_budget_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.create_index('bots_enabled_idx', ['enabled'], unique=False, postgresql_where=sa.text('enabled'))

    op.create_table('kill_switch',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('engaged', sa.Boolean(), nullable=False),
    sa.Column('engaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('engaged = false or engaged_at is not null', name='kill_switch_engaged_needs_time'),
    sa.CheckConstraint('id = 1', name='kill_switch_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('bot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('audit_bot_occurred_idx', ['bot_id', 'occurred_at'], unique=False)
        batch_op.create_index('audit_event_occurred_idx', ['event_type', 'occurred_at'], unique=False)
        batch_op.create_index('audit_occurred_idx', ['occurred_at'], unique=False)

    op.create_table('backtest_equity_points',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('bar_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'bar_index', name='backtest_equity_run_bar_uniq')
    )
    with op.batch_alter_table('backtest_equity_points', schema=None) as batch_op:
        batch_op.create_index('backtest_equity_run_idx', ['run_id', 'bar_index'], unique=False)

    op.create_table('equity_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('bot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cash', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.CheckConstraint('drawdown >= 0', name='equity_drawdown_non_negative'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index('equity_bot_captured_idx', ['bot_id', 'captured_at'], unique=False)
        batch_op.create_index('equity_captured_idx', ['captured_at'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('bot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('client_order_id', sa.Text(), nullable=False),
    sa.Column('broker_order_id', sa.Text(), nullable=True),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('side', sa.Text(), nullable=False),
    sa.Column('order_type', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('time_in_force', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('bar_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('blocked_by_rule', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("mode in ('paper', 'live')", name='orders_mode_check'),
    sa.CheckConstraint("order_type in ('market', 'limit', 'stop', 'stop_limit')", name='orders_type_check'),
    sa.CheckConstraint("order_type not in ('limit', 'stop_limit') or limit_price is not null", name='orders_limit_price_required'),
    sa.CheckConstraint("order_type not in ('stop', 'stop_limit') or stop_price is not null", name='orders_stop_price_required'),
    sa.CheckConstraint("side in ('buy', 'sell')", name='orders_side_check'),
    sa.CheckConstraint("status <> 'blocked' or blocked_by_rule is not null", name='orders_blocked_needs_rule'),
    sa.CheckConstraint("status in ('pending', 'submitted', 'partial', 'filled', 'cancelled', 'rejected', 'blocked', 'expired')", name='orders_status_check'),
    sa.CheckConstraint('qty > 0', name='orders_qty_positive'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_order_id'),
    sa.UniqueConstraint('client_order_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index('orders_bot_id_idx', ['bot_id'], unique=False)
        batch_op.create_index('orders_bot_symbol_bar_uniq', ['bot_id', 'symbol', 'bar_timestamp'], unique=True, postgresql_where=sa.text('bot_id is not null and bar_timestamp is not null'), sqlite_where=sa.text('bot_id is not null and bar_timestamp is not null'))
        batch_op.create_index('orders_open_idx', ['requested_at'], unique=False, postgresql_where=sa.text("status in ('pending', 'submitted', 'partial')"))
        batch_op.create_index('orders_status_requested_idx', ['status', 'requested_at'], unique=False)
        batch_op.create_index('orders_symbol_requested_idx', ['symbol', 'requested_at'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('bot_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('entry_price > 0', name='positions_entry_price_positive'),
    sa.CheckConstraint('qty <> 0', name='positions_qty_nonzero'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'symbol', name='positions_bot_symbol_uniq')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index('positions_bot_id_idx', ['bot_id'], unique=False)

    op.create_table('fills',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), sa.Identity(always=True), nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('broker_fill_id', sa.Text(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('commission >= 0', name='fills_commission_non_negative'),
    sa.CheckConstraint('price > 0', name='fills_price_positive'),
    sa.CheckConstraint('qty > 0', name='fills_qty_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_fill_id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index('fills_filled_at_idx', ['filled_at'], unique=False)
        batch_op.create_index('fills_order_id_idx', ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index('fills_order_id_idx')
        batch_op.drop_index('fills_filled_at_idx')

    op.drop_table('fills')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index('positions_bot_id_idx')

    op.drop_table('positions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('orders_symbol_requested_idx')
        batch_op.drop_index('orders_status_requested_idx')
        batch_op.drop_index('orders_open_idx', postgresql_where=sa.text("status in ('pending', 'submitted', 'partial')"))
        batch_op.drop_index('orders_bot_symbol_bar_uniq', postgresql_where=sa.text('bot_id is not null and bar_timestamp is not null'), sqlite_where=sa.text('bot_id is not null and bar_timestamp is not null'))
        batch_op.drop_index('orders_bot_id_idx')

    op.drop_table('orders')
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index('equity_captured_idx')
        batch_op.drop_index('equity_bot_captured_idx')

    op.drop_table('equity_snapshots')
    with op.batch_alter_table('backtest_equity_points', schema=None) as batch_op:
        batch_op.drop_index('backtest_equity_run_idx')

    op.drop_table('backtest_equity_points')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('audit_occurred_idx')
        batch_op.drop_index('audit_event_occurred_idx')
        batch_op.drop_index('audit_bot_occurred_idx')

    op.drop_table('audit_log')
    op.drop_table('kill_switch')
    with op.batch_alter_table('bots', schema=None) as batch_op:
        batch_op.drop_index('bots_enabled_idx', postgresql_where=sa.text('enabled'))

    op.drop_table('bots')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index('backtest_symbol_created_idx')
        batch_op.drop_index('backtest_strategy_created_idx')

    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
