"""live gating: approval queue and live settings

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-02 16:33:44.997044
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Autogenerate renders postgresql.JSONB as JSONB(astext_type=Text()), a bare
# name it does not import. Kept here so generated migrations are runnable.
from sqlalchemy import Text  # noqa: F401


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Frozen in this migration on purpose. Referencing the live model would make
# what this migration does change whenever the model does, and a migration that
# is not fixed in time cannot be replayed.
STATUSES_BEFORE = (
    'pending', 'submitted', 'partial', 'filled', 'cancelled', 'rejected',
    'blocked', 'expired',
)
STATUSES_AFTER = (
    'pending', 'awaiting_approval', 'submitted', 'partial', 'filled',
    'cancelled', 'rejected', 'blocked', 'expired',
)


def _status_check(values) -> str:
    joined = ', '.join(f"'{value}'" for value in values)
    return f'status in ({joined})'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_settings',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('auto_approve', sa.Boolean(), nullable=False),
    sa.Column('auto_approve_note', sa.Text(), nullable=True),
    sa.Column('auto_approve_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_order_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('approval_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('approval_timeout_seconds > 0', name='live_settings_timeout_positive'),
    sa.CheckConstraint('auto_approve = false or (auto_approve_note is not null and auto_approve_enabled_at is not null)', name='live_settings_auto_approve_needs_note'),
    sa.CheckConstraint('id = 1', name='live_settings_singleton'),
    sa.CheckConstraint('max_order_value >= 0', name='live_settings_ceiling_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_requested_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('approval_note', sa.Text(), nullable=True))
        batch_op.create_index('orders_awaiting_approval_idx', ['approval_requested_at'], unique=False, postgresql_where=sa.text("status = 'awaiting_approval'"))
        batch_op.create_check_constraint('orders_awaiting_needs_request_time', "status <> 'awaiting_approval' or approval_requested_at is not null")
        # Autogenerate detects added and dropped constraints but not a changed
        # expression on an existing one, so this was missing and an
        # 'awaiting_approval' insert failed against the migrated schema.
        batch_op.drop_constraint('orders_status_check', type_='check')
        batch_op.create_check_constraint(
            'orders_status_check', _status_check(STATUSES_AFTER)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # Any order still awaiting approval cannot exist under the narrower status
    # list. Cancelled is the truthful resolution: it never reached the broker,
    # so nothing is being undone at the venue. Without this the downgrade fails
    # on exactly the databases where the feature was used, and leaves a
    # half-rebuilt table behind.
    op.execute(
        "update orders set status = 'cancelled' where status = 'awaiting_approval'"
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_status_check', type_='check')
        batch_op.create_check_constraint(
            'orders_status_check', _status_check(STATUSES_BEFORE)
        )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_awaiting_needs_request_time', type_='check')
        batch_op.drop_index('orders_awaiting_approval_idx', postgresql_where=sa.text("status = 'awaiting_approval'"))
        batch_op.drop_column('approval_note')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approval_requested_at')

    op.drop_table('live_settings')
    # ### end Alembic commands ###
