version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: trading-platform-db
    environment:
      POSTGRES_DB: trading_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trading-network

  redis:
    image: redis:7-alpine
    container_name: trading-platform-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trading-network

  python-backend:
    build:
      context: ./python_backend
      dockerfile: Dockerfile
    container_name: trading-platform-python
    environment:
      - TRADING_MODE=paper
    ports:
      - "8000:8000"
    networks:
      - trading-network
    env_file:
      - ./python_backend/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: trading-platform-server
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=trading_platform
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHON_BACKEND_URL=http://python-backend:8000
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
      - python-backend
    networks:
      - trading-network
    env_file:
      - ./server/.env

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: trading-platform-web
    ports:
      - "5173:80"
    depends_on:
      - server
    networks:
      - trading-network

volumes:
  postgres_data:
  redis_data:

networks:
  trading-network:
    driver: bridge
